require('jquery');
require('popper.js');
//require('popper');
//require('./bootstrap');
require('pace');
require('perfect-scrollbar');
require('@coreui/coreui');
require('chart.js');
//require('chart');